version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.8
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
  - dependency-name: "@umijs/test"
    versions:
    - 3.3.10
    - 3.3.7
    - 3.3.9
    - 3.4.0
    - 3.4.1
    - 3.4.2
    - 3.4.3
    - 3.4.4
    - 3.4.6
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
  - dependency-name: antd
    versions:
    - 4.11.2
    - 4.12.0
    - 4.12.1
    - 4.12.2
    - 4.12.3
    - 4.13.0
    - 4.13.1
    - 4.14.0
    - 4.14.1
  - dependency-name: "@umijs/preset-react"
    versions:
    - 1.7.13
    - 1.8.0
    - 1.8.1
    - 1.8.2
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
  - dependency-name: less-loader
    versions:
    - 7.3.0
  - dependency-name: "@umijs/fabric"
    versions:
    - 2.5.6
  - dependency-name: less
    versions:
    - 3.13.1
