name: NPM publish package verification 
on:
  push:
    branches:
    - 'canary'
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: node script/discover.js
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}