name: npm publish package verification 
on:
  pull_request:
    branches:
    - 'canary'
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: node script/discover.js
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}