name: npm publish package canary
on:
  push:
    branches:
    - 'canary'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: cd packages/react-ui && npm install
    - run: node script/release-canary.js
    - run: cd packages/react-ui && npm publish --access public --tag canary
    - run: git push
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}